language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

# silence a warning message on travis
install:
  - python --version

# the original package does not have any tests, and it would be difficult to
# write consistent ones, so we only install the package which will make sure
# the package will compile
script:
  - python setup.py clean build
  - python setup.py clean sdist
  - python setup.py clean bdist
  - python setup.py clean bdist_egg
  - python setup.py clean && pip install .
  - python -c "import netifaces"
