language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

# the original package does not have any tests, and it would be difficult to
# write consistent ones, so we only install the package which will make sure
# the package will compile
script:
  - pip install .
